//! { signal: [
//!   ['spi',
//!  { name: "cs",    wave: "1..0...............1..." },
//!  { name: "sclk",  wave: "P.P.P.P.P.P.P.P.P.P.P.P.P" },
//!  { name: "mosi",  wave: "x...0.....4.x...........", data: [ "addr"] },
//!  { name: "miso",  wave: "x...........3.......x...", data: ["data"] },
//!  ],
//!  {},
//!  {},

//! ],

//!  head:{
//!     text:'WaveDrom spi example for a read cycle for a single address',
//!     tick:0,
//!     every:2
//!   }}

//! SPI Protocol Specification
//! 1. Overview
//! The Serial Peripheral Interface (SPI) is a synchronous serial communication interface specification used for short-distance communication, primarily in embedded systems. It facilitates full-duplex communication between one master device and one or more slave devices.

//! 2. Interface Signals
//! Master Out Slave In (MOSI): The data line used by the master to send data to the slaves.
//! Master In Slave Out (MISO): The data line used by the slaves to send data back to the master.
//! Serial Clock (SCLK): The clock generated by the master to synchronize data transmission.
//! Chip Select (CS): An active-low signal used by the master to select and enable a specific slave for communication.
//! 3. Communication Mode
//! SPI communication is based on a master-slave architecture, where the master device controls the timing of the clock signal and the selection of slave devices through the chip select lines. Data can be exchanged between the master and the selected slave(s) using the MOSI and MISO lines.

//! 4. Data Format
//! Bit Order: Data & Address is transmitted MSB first
//!
//! *DUT Specification*
//! 1. When the DUT receives start (high for at least 160ns) the design starts 4 reading cycles from the spi from addresses 0x0-0x3 and after receiving the information for each of the addresses the information is output in parallel at the Data Out ports according to the address.

//! 2. While reading the 4 channels the DUT will ignore start until after the end of the 4 reading cycles
module spi_master (
    input clk, //! 100 MHz
    input rst,  //! active high
    input start, //! Start signal for reading addresses - active high
    output reg [1:0] addr, //! Data Out address - 0x0-0x3
    output reg [7:0] data, //! Data Out data - according spi data
    output reg valid, //! Indication for sampling Data Out data & addr
    input miso, //! Master In Slave Out
    output reg mosi, //! Master Out Slave In
    output reg sclk, //! 6.25 MHz 
    output reg cs //! active low
);

    // Define states with enum for better readability in waveforms
    typedef enum logic [2:0] {
        IDLE = 3'b000,
        WAIT_FOR_START = 3'b001,
        BUILD_CMD = 3'b010,
        MASTER = 3'b011,
        SLAVE = 3'b100,
        READ_DATA = 3'b101,
        VALID_DATA = 3'b110
    } state_type;


    state_type state;
    reg [5:0] bit_count; // to count bits transmitted/received
    reg [7:0] shift_reg; // to shift data in/out
    reg [1:0] channel; // to keep track of current channel

    // Clock division for sclk (SPI clock)
    reg [3:0] clock_divider;

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            clock_divider <= 0;
            sclk <= 0;
            state <= IDLE;
            cs <= 1;
            addr <= 0;
            data <= 0;
            mosi<= 0;
        end else begin

            clock_divider <= clock_divider + 1;
            sclk <= clock_divider[3]; // Example clock division
            
        end
    end


    always @(posedge sclk ) begin
        case (state)
            IDLE: begin
                valid <= 0;
                if (channel < 3)begin
                    channel <= channel + 1;
                    state <= BUILD_CMD;
                end
                else begin
                    channel <= 0;
                    state <= WAIT_FOR_START;
                end
                
                
            end
            WAIT_FOR_START: begin
                if (start) begin
                    state <= BUILD_CMD;
                end else
                    state <= WAIT_FOR_START;
            end
            BUILD_CMD: begin
                shift_reg <= {6'b0, channel}; // Load command byte into shift register
                bit_count <= 0;
                state <= MASTER;
            end
            MASTER: begin
                if (sclk) begin
                    cs <= 0; // Activate the chip select
                    mosi <= shift_reg[7];
                    shift_reg <= {shift_reg[6:0], 1'b0}; // Shift out MSB first
                    bit_count <= bit_count + 1;
                    if (bit_count == 8) // Command byte sent
                        state <= SLAVE;
                end
            end
            SLAVE: begin
                if (sclk) begin
                    shift_reg <= shift_reg << 1;  // Shift left by one position
                    shift_reg[0]<= miso; // Shift in MISO MSB-first
                    bit_count <= bit_count + 1;
                    if (bit_count == 16) begin // 8 bits transferred after command
                        state <= VALID_DATA;
                        cs <= 1; // Deactivate chip select
                    end
                end
            end            
            VALID_DATA: begin
                data <= shift_reg[7:0]; // Last 8 bits are data
                addr <= channel;
                valid <= 1;
                state <= IDLE;
            end
            default: state <= IDLE;
        endcase
        
    end
endmodule
